<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CauhoiSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('cauhois')->insert([
            [
                'linhvuc' => '1',
                'trangthai' => '1',
                'cauhoi' => 'Sự xuất hiện của nhà nước cổ đại nào sau đây có nguyên nhân là do mâu thuẫn giai cấp gay gắt đến mức không thể điều hòa được:',
                'dapan1' => 'Nhà nước Giéc – manh.',
                'dapan2' => 'Nhà nước Rôma.',
                'dapan3' => 'Nhà nước Aten.',
                'dapan4' => 'Các Nhà nước phương Đông.',
                'dapandung' => '2',
            ],
            [
                'linhvuc' => '1',
                'trangthai' => '1',
                'cauhoi' => 'Theo học thuyết Mác - Lênin, nhận định nào sau đây là đúng:',
                'dapan1' => 'Tính chất giai cấp của nhà nước không đổi nhưng bản chất của nhà nước thì thay đổi qua các kiểu nhà nước khác nhau.',
                'dapan2' => 'Tính chất giai cấp và bản chất của nhà nước không thay đổi qua các kiểu nhà nước khác nhau.',
                'dapan3' => 'Tính chất giai cấp và bản chất của nhà nước luôn luôn thay đổi qua các kiểu nhà nước khác nhau.',
                'dapan4' => 'Tính chất giai cấp của nhà nước luôn luôn thay đổi, còn bản chất của nhà nước là không đổi qua các kiểu nhà nước khác nhau.',
                'dapandung' => '2',
            ],
            [
                'linhvuc' => '1',
                'trangthai' => '1',
                'cauhoi' => 'Thành phố nào sau đây không phải là thành phố trực thuộc trung ương:',
                'dapan1' => 'Thành phố Huế',
                'dapan2' => 'Thành phố Cần Thơ',
                'dapan3' => 'Thành phố Đà Nẵng',
                'dapan4' => 'Thành phố Hải Phòng',
                'dapandung' => '1',
            ],
            [
                'linhvuc' => '1',
                'trangthai' => '1',
                'cauhoi' => 'Câu nào sau đây đúng với quy định được ghi trong Điều 15 Hiến pháp Việt Nam 1992, đã được sửa đổi, bổ sung:',
                'dapan1' => '“…Nhà nước thực hiện nhất quán chính sách phát triển nền kinh tế thị trường có sự quản lý của nhà nước theo định hướng XHCN…”.',
                'dapan2' => '“…Nhà nước thực hiện nhất quán chính sách phát triển nền kinh tế thị trường định hướng XHCN…”.',
                'dapan3' => '“…Nhà nước thực hiện nhất quán chính sách phát triển nền kinh tế thị trường tự do cạnh tranh theo định hướng XHCN…”.',
                'dapan4' => '“…Nhà nước thực hiện nhất quán chính sách phát triển nền kinh tế thị trường kết hợp với kế hoạch phát triển kinh tế của nhà nước theo định hướng XHCN…”.',
                'dapandung' => '1',
            ],
            [
                'linhvuc' => '1',
                'trangthai' => '1',
                'cauhoi' => 'Sự tồn tại của nhà nước:',
                'dapan1' => 'Là kết quả tất yếu của xã hội loài người, ở đâu có xã hội ở đó tồn tại nhà nước',
                'dapan2' => 'Là kết quả tất yếu của xã hội có giai cấp',
                'dapan3' => 'Là do ý chí của các thành viên trong xã hội với mong muốn thành lập nên nhà nước để bảo vệ lợi ích chung.',
                'dapan4' => 'Cả A, B và C đều đúng',
                'dapandung' => '4',
            ],
            [
                'linhvuc' => '1',
                'trangthai' => '1',
                'cauhoi' => 'Số lượng tỉnh, thành phố trực thuộc trung ương hiện nay của nước CHXHCN Việt Nam là:',
                'dapan1' => '62',
                'dapan2' => '63',
                'dapan3' => '64',
                'dapan4' => '65',
                'dapandung' => '2',
            ],
            [
                'linhvuc' => '1',
                'trangthai' => '1',
                'cauhoi' => 'Quyền lực và hệ thống tổ chức quyền lực trong xã hội CXNT:',
                'dapan1' => 'Hòa nhập vào xã hội và phục vụ lợi ích cho các thành viên trong xã hội.',
                'dapan2' => 'Đứng trên xã hội, tách khỏi xã hội và phục vụ lợi ích cho Hội đồng thị tộc, tù trưởng, các thủ lĩnh tôn giáo.',
                'dapan3' => 'Đứng trên xã hội, tách khỏi xã hội và phục vụ lợi ích cho các thành viên trong xã hội.',
                'dapan4' => 'Hòa nhập vào xã hội và phục vụ cho lợi ích của Hội đồng thị tộc, tù trưởng, các thủ lĩnh tôn giáo.',
                'dapandung' => '1',
            ],
            [
                'linhvuc' => '1',
                'trangthai' => '1',
                'cauhoi' => 'Ngoài tính chất giai cấp, kiểu nhà nước nào sau đây còn có vai trò xã hội:',
                'dapan1' => 'Nhà nước XHCN',
                'dapan2' => 'Nhà nước XHCN; Nhà nước tư sản',
                'dapan3' => 'Nhà nước XHCN; Nhà nước tư sản; Nhà nước phong kiến',
                'dapan4' => 'Nhà nước XHCN; Nhà nước tư sản; Nhà nước phong kiến; Nhà nước chủ nô',
                'dapandung' => '1',
            ],
            [
                'linhvuc' => '1',
                'trangthai' => '1',
                'cauhoi' => 'Theo Hiến pháp Việt Nam 1992, Thủ tướng Chính phủ Nước CHXHCN Việt Nam:',
                'dapan1' => 'Do nhân dân bầu',
                'dapan2' => 'Do Quốc hội bầu theo sự giới thiệu của Chủ tịch nước',
                'dapan3' => 'Do Chủ tịch nước giới thiệu',
                'dapan4' => 'Do Chính phủ bầu',
                'dapandung' => '2',
            ],            
            [
                'linhvuc' => '1',
                'trangthai' => '1',
                'cauhoi' => 'Theo Điều lệ ĐCS Việt Nam, nếu không có đại hội bất thường, thì mấy năm ĐCS Việt Nam tổ chức Đại hội đại biểu toàn quốc một lần:',
                'dapan1' => '3 năm',
                'dapan2' => '4 năm',
                'dapan3' => '5 năm',
                'dapan4' => '6 năm',
                'dapandung' => '3',
            ],            
            [
                'linhvuc' => '2',
                'trangthai' => '1',
                'cauhoi' => 'Bấm tổ hợp phím Ctrl + S trong Microsoft Word 2010 sẽ thực hiện chức năng gì:',
                'dapan1' => 'Mở một tài liệu mới',
                'dapan2' => 'Mở một tài liệu có sẵn trong đĩa',
                'dapan3' => 'Lưu tài liệu hiện tại',
                'dapan4' => 'Đóng chương trình Microsoft Word 2010',
                'dapandung' => '3',
            ],
            [
                'linhvuc' => '2',
                'trangthai' => '1',
                'cauhoi' => 'Để phóng to/thu nhỏ tài liệu trong Microsoft Word 2010, ta thực hiện bằng cách nào:',
                'dapan1' => 'Giữ phím Ctrl và di chuyển con xoay trên con chuột.',
                'dapan2' => 'Điều khiển thanh trượt zoom ở góc phải bên dưới màn hình Word',
                'dapan3' => 'Cả phương án 1 và 2 đều đúng',
                'dapan4' => 'Cả phương án 1 và 2 đều sai',
                'dapandung' => '3',
            ],
            [
                'linhvuc' => '2',
                'trangthai' => '1',
                'cauhoi' => 'Có thể thoát chương trình Microsoft Word 2010 bằng cách:',
                'dapan1' => 'Kích chuột vào thẻ File/Exit.',
                'dapan2' => 'Bấm tổ hợp phím Ctrl + F4',
                'dapan3' => 'Click chuột vào biểu tượng Close () của cửa sổ chương trình.',
                'dapan4' => 'Cả 3 phương án trên đều đúng',
                'dapandung' => '4',
            ],
            [
                'linhvuc' => '2',
                'trangthai' => '1',
                'cauhoi' => 'Bấm tổ hợp phím Ctrl + N trong Microsoft Word 2010 sẽ thực hiện chức năng gì:',
                'dapan1' => 'Mở một tài liệu mới',
                'dapan2' => 'Mở một tài liệu có sẵn trong đĩa',
                'dapan3' => 'Lưu một tài liệu',
                'dapan4' => 'Mở một tài liệu mới trống hoặc mở 1 tài liệu mới theo mẫu.',
                'dapandung' => '4',
            ],
            [
                'linhvuc' => '2',
                'trangthai' => '1',
                'cauhoi' => 'Bấm tổ hợp phím Ctrl + O trong Microsoft Word 2010 sẽ thực hiện chức năng gì:',
                'dapan1' => 'Mở một tài liệu mới',
                'dapan2' => 'Mở một tài liệu có sẵn trong đĩa',
                'dapan3' => 'Lưu một tài liệu',
                'dapan4' => 'Đóng chương trình Microsoft Word 2010',
                'dapandung' => '2',
            ],
            [
                'linhvuc' => '2',
                'trangthai' => '1',
                'cauhoi' => 'Bấm tổ hợp phím Ctrl + B trong Microsoft Word 2010 sẽ thực hiện chức năng gì cho khối văn bản đang chọn:',
                'dapan1' => 'Bật/Tắt chữ đậm',
                'dapan2' => 'Bật/Tắt chữ nghiêng',
                'dapan3' => 'Bật/Tắt chữ gạch chân',
                'dapan4' => 'Bật/Tắt chữ chỉ số dưới (Bottom)',
                'dapandung' => '1',
            ],
            [
                'linhvuc' => '2',
                'trangthai' => '1',
                'cauhoi' => 'Bấm tổ hợp phím Ctrl + I trong Microsoft Word 2010 sẽ thực hiện chức năng gì cho khối văn bản đang chọn:',
                'dapan1' => 'Bật/Tắt chữ đậm',
                'dapan2' => 'Bật/Tắt chữ nghiêng',
                'dapan3' => 'Bật/Tắt chữ gạch chân',
                'dapan4' => 'Bật/Tắt chữ chỉ số dưới (Bottom)',
                'dapandung' => '2',
            ],
            [
                'linhvuc' => '2',
                'trangthai' => '1',
                'cauhoi' => 'Bấm tổ hợp phím Ctrl + U trong Microsoft Word 2010 sẽ thực hiện chức năng gì cho khối văn bản đang chọn:',
                'dapan1' => 'Bật/Tắt chữ đậm',
                'dapan2' => 'Bật/Tắt chữ nghiêng',
                'dapan3' => 'Bật/Tắt chữ gạch chân',
                'dapan4' => 'Bật/Tắt chữ chỉ số dưới (Bottom)',
                'dapandung' => '3',
            ],
            [
                'linhvuc' => '2',
                'trangthai' => '1',
                'cauhoi' => 'Bấm tổ hợp phím Ctrl + Shift + = trong Microsoft Word 2010 sẽ thực hiện chức năng gì cho khối văn bản đang chọn:',
                'dapan1' => 'Bật/Tắt chữ chỉ số trên',
                'dapan2' => 'Bật/Tắt chữ chỉ số dưới',
                'dapan3' => 'Bật/Tắt chữ hoa',
                'dapan4' => 'Bật/Tắt chữ thường',
                'dapandung' => '1',
            ],
            [
                'linhvuc' => '2',
                'trangthai' => '1',
                'cauhoi' => 'Bấm tổ hợp phím Ctrl + = trong Microsoft Word 2010 sẽ thực hiện chức năng gì cho khối văn bản đang chọn:',
                'dapan1' => 'Bật/Tắt chữ chỉ số trên',
                'dapan2' => 'Bật/Tắt chữ chỉ số dưới',
                'dapan3' => 'Bật/Tắt chữ hoa',
                'dapan4' => 'Bật/Tắt chữ thường',
                'dapandung' => '2',
            ],
        ]);
    }
}
